# **U23AI021 - DL Lab – 1**

## **Q.1 PyTorch Tensors and Basic Operations**

In [5]:
#part a

import torch


a = torch.tensor(5)
print("Scalar:", a)

b = torch.tensor([1, 2, 3])
print("Vector:", b)

c = torch.tensor([[1, 2], [3, 4]])
print("Matrix:\n", c)
#randomly chosen tewnsor
d = torch.rand(3, 3)
print("Random Tensor:\n", d)


e = torch.zeros(2, 2)
f = torch.ones(2, 2)
print("Zeros:\n", e)
print("Ones:\n", f)

#dtype = torch.float hyperparamter add kari devanu bas
g = torch.tensor([1, 2, 3], dtype=torch.float32)
print("Data Type:", g.dtype)

Scalar: tensor(5)
Vector: tensor([1, 2, 3])
Matrix:
 tensor([[1, 2],
        [3, 4]])
Random Tensor:
 tensor([[0.3820, 0.0555, 0.1540],
        [0.4132, 0.5711, 0.3741],
        [0.3567, 0.9024, 0.0045]])
Zeros:
 tensor([[0., 0.],
        [0., 0.]])
Ones:
 tensor([[1., 1.],
        [1., 1.]])
Data Type: torch.float32


In [6]:
#part b

x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

print("Add:", x + y) # basic Arithmetic ops -. as it is
print("Multiply:", x * y)


m = torch.tensor([[1, 2, 3]])
print("Broadcasting:\n", m + x)


print("First element:", x[0]) # Indexing


r = torch.arange(6) # Reshape b thai shake aa rite
print("Reshaped:\n", r.reshape(2, 3))


Add: tensor([5, 7, 9])
Multiply: tensor([ 4, 10, 18])
Broadcasting:
 tensor([[2, 4, 6]])
First element: tensor(1)
Reshaped:
 tensor([[0, 1, 2],
        [3, 4, 5]])


In [7]:
#part c
# autograde diff by pytorch
#for that hyp para requires_grad = true kari de and then .bwd call kari daiye for bwd pass


x = torch.tensor(2.0, requires_grad=True)
y = x ** 3 + 2 * x

y.backward()

#.GRAD will store the ans
print("Gradient dy/dx:", x.grad)

Gradient dy/dx: tensor(14.)


# Q2. **Linear Alegebra** in tensorflow

In [8]:
import tensorflow as tf

A = tf.constant([[1, 2],  [3, 4]], dtype=tf.float32)
B = tf.constant([[5, 6],[7, 8]], dtype=tf.float32)

print("Addition:\n", tf.add(A, B))
print("Matrix Multiply:\n", tf.matmul(A, B)) #matmul

print("Transpose:\n", tf.transpose(A))

#sub functions in lialg
print("Determinant:", tf.linalg.det(A))
print("Inverse:\n", tf.linalg.inv(A))

Addition:
 tf.Tensor(
[[ 6.  8.]
 [10. 12.]], shape=(2, 2), dtype=float32)
Matrix Multiply:
 tf.Tensor(
[[19. 22.]
 [43. 50.]], shape=(2, 2), dtype=float32)
Transpose:
 tf.Tensor(
[[1. 3.]
 [2. 4.]], shape=(2, 2), dtype=float32)
Determinant: tf.Tensor(-2.0, shape=(), dtype=float32)
Inverse:
 tf.Tensor(
[[-2.0000002   1.0000001 ]
 [ 1.5000001  -0.50000006]], shape=(2, 2), dtype=float32)


# Q3. hard coded with just numpy for ***AND & OR Gates using Perceptron***

In [10]:
import numpy as np

def perceptron(x, w, b):
    return 1 if np.dot(x, w) + b >= 0 else 0

inputs = np.array([[0,0], [0,1], [1,0], [1,1]])

# AND
w_and = np.array([1, 1])
b_and = -1.5

print("AND op")
for x in inputs:
    print(x, perceptron(x, w_and, b_and))

# OR
w_or = np.array([1, 1])
b_or = -0.5

print("\nOR op")
for x in inputs:
    print(x, perceptron(x, w_or, b_or))

AND op
[0 0] 0
[0 1] 0
[1 0] 0
[1 1] 1

OR op
[0 0] 0
[0 1] 1
[1 0] 1
[1 1] 1


# **Q4. XOR Problem using PyTorch Neural NW**

In [11]:
import torch
import torch.nn as nn
import torch.optim as optim

#ip
X = torch.tensor([[0.,0.], [0.,1.], [1.,0.], [1.,1.]])
Y = torch.tensor([[0.], [1.], [1.], [0.]])

model = nn.Sequential(
    nn.Linear(2, 4),
    nn.ReLU(),
    nn.Linear(4, 1),
    nn.Sigmoid()
)

#loass and optimizing
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.1)

#train for 200 epochs
for epoch in range(2000):
    optimizer.zero_grad()
    output = model(X)
    loss = criterion(output, Y)
    loss.backward()
    optimizer.step()


print("XOR op:")
print(model(X).detach())

XOR op:
tensor([[4.5647e-06],
        [9.9989e-01],
        [9.9999e-01],
        [1.0014e-05]])


# **Q.5 Regressive Simple NN**

In [13]:
import torch
import torch.nn as nn
import torch.optim as optim

# y=2x
X = torch.unsqueeze(torch.linspace(0, 10, 20), 1)
Y = 2 * X

model = nn.Sequential(
    nn.Linear(1, 10),
    nn.ReLU(),
    nn.Linear(10, 1)
)

criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)

for epoch in range(1000):
    optimizer.zero_grad()
    y_pred = model(X)
    loss = criterion(y_pred, Y)
    loss.backward()
    optimizer.step()

print("Regression ans:")
print(model(torch.tensor([[5.0]])).item())

Regression ans:
9.982754707336426
